### ISSUE TITLE
comment underscores

### ISSUE THREAD

**Issue by mehdipourfar** [bbatsov/prelude#1067] opened 2017-02-12 18:11 UTC
Please, take a look at this image.
![screenshot from 2017-02-12 21 34 57](https://cloud.githubusercontent.com/assets/13090047/22864744/1df2b8aa-f16c-11e6-93fd-891b6488ab3a.png)

There are always some underscores under certain words of my comments.
I can't understand what they indicate. How can I get rid of them?

**Comment by AlainODea** [comment] 2017-02-18 19:14
@mehdipourfar I can't reproduce this. I suspect some undesired minor mode is enabled.

Is this happening with no customizations of Emacs Prelude?

I created a file called **example** with this content, closed it and reopened it:

```python
#!/usr/bin/env python3

"""
requirements:
pip install pycrypto==2.6.1

"""

import json
import sys
import struct
```

The Major Mode is reported as **Python**.

The Minor Modes are:
* guru - guru-mode
* company - company-mode
* EditorConfig - editorconfig-mode
* ws - whitespace-mode
* Projectile[Scripts] - projectile-mode
* Pre - prelude-mode
* WK - which-key-mode
* (*) - beacon-mode
* SP -smartparens-mode
* FlyC:0/3 - flycheck-mode

**Comment by mehdipourfar** [comment] 2017-04-01 19:17
I finally found the issue. My problem was with flyspell-mode.

**Comment by AlainODea** [comment] 2017-04-01 22:31
@mehdiporter good stuff. Please close this issue :)

**Closed** 2017-04-02 19:57 UTC
